#!/bin/bash

# Quick Database Switch Script
echo "=== Quick Database Switch ==="
echo ""
echo "Your data is backed up in: neon-backup.sql (55KB)"
echo ""
echo "To switch to a new PostgreSQL database:"
echo ""
echo "1. Get a free PostgreSQL database from:"
echo "   - Supabase.com (500MB free) - Recommended"
echo "   - ElephantSQL.com (20MB free)"
echo "   - Aiven.io (1 month free trial)"
echo ""
echo "2. They will give you a connection string like:"
echo "   postgresql://user:password@host:port/database"
echo ""
echo "3. In Replit, go to Secrets (lock icon) and update:"
echo "   DATABASE_URL = [your new connection string]"
echo ""
echo "4. Run this command to import your data:"
echo "   psql \$DATABASE_URL < neon-backup.sql"
echo ""
echo "That's it! Your app will automatically use the new database."